### PR TITLE
Fix incorrect textHeight

### PR DESCRIPTION
**Pull request by vroad**
LINE_HEIGHT + DESCENDER? Looks incorrect.

### CODE REVIEW

**Comment by larsiusprime** [comment]
Did you check this against the text metrics demo?

**Comment by tocsick** [comment]
He's right that LINE_HEIGHT + DESCENDER is incorrect, LINE_HEIGHT includes DESCENDER already (it was my fault, I was fiddling with it when playing with the text renderer). But the if statement following needs to be updated too. The whole thing should be:

    th += __getLineMetric( i, ASCENDER ) + __getLineMetric( i, DESCENDER );
    if ( i != numLines - 1 ) {
        th += __getLineMetric( i, LEADING );
    }

**Comment by larsiusprime** [comment]
Cool :) Just double checking that the intuition (which of course sounds right) matches the expected visual results.

**Comment by vroad** [comment]
TextMetrics is broken with/without that fix. I'm not sure why text is rendered here.

**Comment by vroad** [comment]
My fix was correct? Then there might be other places which we still need to fix...

**Comment by tocsick** [comment]
@vroad the if statement following the line you fixed needs to be updated to account for leading. At present it is removing non-existing leading on the last line.

**Comment by vroad** [comment]
I've changed that too but TextMetrics is still broken.

**Pull request merged**
