### PR TITLE
changes required for Starling's render texture and stencil masking

### PR DESCRIPTION
**Pull request by peteshand**

### CODE REVIEW

**Comment by peteshand** [comment]
Hey guys, can someone please review this pull request. it's been 28 days with all auto tests passing. I'm happy to make changes if need be, but need some feedback. Cheers

**Comment by DanielUranga** [comment]
Could you make an example project that I can test with current version of OpenFL, see it not working -> apply this patch -> test and see it working?

**Comment by peteshand** [comment]
No worries.
I've create two example projects. One with the updates and one without.

Source files can be downloaded from: http://peteshand.net/starling/openfl_context3d_masking/MaskIssueExamples.zip

Online example with updates applied can be viewed here:
http://peteshand.net/starling/openfl_context3d_masking/withUpdate/

Online example without updates applied can be viewed here:
http://peteshand.net/starling/openfl_context3d_masking/withoutUpdate/

Currently to get around this issue I'm embedding my own version of openfl.display3d.Context3D within the Starling library and overriding the standard one with a typedef. While this technically works, it's far from ideal as every time there are changes to Context3D in openfl I need to manually copy the changes across.

**Comment by peteshand** [comment]
oh, forgot to mention. Once the link loads, click on "Masks"

**Comment by peteshand** [comment]
Hey @DanielUranga 
Let me know if you need anything else.

**Comment by peteshand** [comment]
hello?

**Comment by DanielUranga** [comment]
Sorry, I must have something misconfigured so I don't get mail notifications. Will test tonight.

**Comment by DanielUranga** [comment]
The test works perfectly for html5, but for cpp I get:

```
duplicate symbol __ZN6openfl9display3D8textures11Texture_obj13__CreateEmptyEv in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures11Texture_obj6__bootEv in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures11Texture_obj10__registerEv in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures11Texture_obj40uploadCompressedTextureFromByteArray_dynEv in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures11Texture_obj23uploadFromByteArray_dynEv in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures11Texture_obj24uploadFromUInt8Array_dynEv in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures11Texture_obj24uploadFromBitmapData_dynEv in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures11Texture_objC2Ev in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures11Texture_objC1Ev in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures11Texture_obj5__newEN2hx9ObjectPtrINS0_13Context3D_objEEENS4_IN4lime8graphics6opengl13GLTexture_objEEEbii in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures11Texture_obj11__constructEN2hx9ObjectPtrINS0_13Context3D_objEEENS4_IN4lime8graphics6opengl13GLTexture_objEEEbii in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures33__Texture_objuploadFromUInt8ArrayEPN2hx6ObjectERK7DynamicS7_ in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures33__Texture_objuploadFromBitmapDataEPN2hx6ObjectERK7DynamicS7_ in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures49__Texture_objuploadCompressedTextureFromByteArrayEPN2hx6ObjectERK7DynamicS7_S7_ in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures32__Texture_objuploadFromByteArrayEPN2hx6ObjectERK7DynamicS7_S7_ in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures11Texture_obj14internalFormatE in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZN6openfl9display3D8textures11Texture_obj8__mClassE in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZTVN6openfl9display3D8textures11Texture_objE in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZTSN6openfl9display3D8textures11Texture_objE in:
    obj/darwin64/ae8d360f_Texture.o
duplicate symbol __ZTIN6openfl9display3D8textures11Texture_objE in:
    obj/darwin64/ae8d360f_Texture.o

....keeps going...
```
 Maybe unrelated. Does it works for you on cpp?

**Comment by peteshand** [comment]
Ok, thanks. Could you send me the source for the test and I'll look into it

**Comment by DanielUranga** [comment]
The same test you posted.
```lime test html5``` worked excellent, but ```lime test cpp``` returns a linker error, but it happens with this patch or without it, maybe it is related to Starling not being tested on Mac cpp.

Also note OpenFL now has a "develop" branch, this PR should be merged there.

**Comment by peteshand** [comment]
Oh yeah actually Starling isn't fully compatible with cpp. Flash/AIR and js are the main focus, so the errors outlined above are simply related to Starling and not the openfl patch.

I'm going to close this pull or request and make a new one on the development branch

**Comment by peteshand** [comment]
moved to: https://github.com/openfl/openfl/pull/1035

**Pull request closed without merging**
