### PR TITLE
Carret fix for empty TextInput for html/js target

### PR DESCRIPTION
**Pull request by ivan-slepchenko**
TextInput not shows caret when its empty, or full of white spaces only.
Also textEngine.__hasFocus never set.

### CODE REVIEW

**Comment by nicholas-slepchenko** [comment]
+1

**Comment by zweimal** [comment]
+1

**Comment by ibilon** [comment]
This is targeting the master branch,
if this still fix issues in the latest version please open a new pull request against the develop branch.

**Comment by loudoweb** [comment]
@ibilon @ivan-slepchenko  I tried last openfl and the issue still exists and this pull request fixes the issue.

**Comment by ibilon** [comment]
Changed the branch to develop and reopened, will do that for the other pull requests that targeted master.

**Pull request closed without merging**
