### PR TITLE
Don't use the framebuffer texture if there are software changes on it.

### LINKED ISSUE #616: BitmapData.draw() before BitmapData.fillRect() causes inconsistent visuals
BitmapData.draw() still has lingering issues with drawSelf.

Some quick screengrab crops-

Correct (flash):
flash

Next (drawSelf = false)
next_drawself_false

Next (drawSelf = true)
next_drawself_true

(Do not next uses Georgia font and Flash uses Times New Roman, that's a separate thing)

Code to reproduce:

```
	private var _matrix:Matrix;
	
	public function new () {
		
		_matrix = new Matrix();
		
		super ();
		textTest();
	}
	
	private function textTest():Void
	{
		var text:TextField = new TextField();
		addChild(text);
		
		text.textColor = 0xFFFF0000;
		text.text = "Hello, World!";
		
		text.x = 5;
		text.y = 5;
		
		var data = new BitmapData(Std.int(text.textWidth+4), Std.int(text.textHeight+4), true);
		var r = new Rectangle(0, 0, data.width, data.height);
		
		// WORKS if drawSelf = true  (text on yellow bkg)
		//!WORKS if drawSelf = false (text on !exist bkg)
		data.draw(text);
		data.fillRect(r, 0xFFFFFF00);
		data.draw(text);
		
		var b = new Bitmap(data);
		b.x = text.x + text.textWidth + 10;
		b.y = text.y;
		addChild(b);
		
		var data2 = new BitmapData(data.width, data.height, true);
		var r2 = new Rectangle(0, 0, data2.width, data2.height);
		
		// WORKS if drawSelf = false (text on yellow bkg)
		// WORKS if drawSelf = true  (text on yellow bkg)
		data2.fillRect(r, 0xFFFFFF00);
		data2.draw(text);
		
		var b2 = new Bitmap(data2);
		b2.x = b.x + b.width + 10;
		b2.y = b.y;
		addChild(b2);
		
		var data3 = new BitmapData(data.width, data.height, true);
		var r3 = new Rectangle(0, 0, data3.width, data3.height);
		
		// WORKS if drawSelf = false (yellow text outlined blue)
		//!WORKS if drawSelf = true  (yellow text)
		drawTextWithBorder(text, data3, 0xFFFFFF00, 0xFF0000FF, 1);
		
		var b3 = new Bitmap(data3);
		b3.x = b2.x + b2.width + 10;
		b3.y = b2.y;
		addChild(b3);
	}
	
	private function drawTextWithBorder(txt:TextField, bmp:BitmapData, color:Int, outlineColor:Int, border:Int)
	{
		drawOutline(txt, bmp, border, outlineColor);
		var oldcolor = txt.textColor;
		txt.textColor = color;
		bmp.draw(txt);
		txt.textColor = oldcolor;
	}
	
	private function drawOutline(txt:TextField, bmp:BitmapData, offset:Int, color:Int)
	{
		_matrix.identity();
		
		var oldcolor = txt.defaultTextFormat.color;
		
		txt.textColor = color;
		
		copyTextWithOffset( -offset, -offset, txt, bmp);
		copyTextWithOffset( offset, 0, txt, bmp);
		copyTextWithOffset( offset, 0, txt, bmp);
		copyTextWithOffset( 0, offset, txt, bmp);
		copyTextWithOffset( 0, offset, txt, bmp);
		copyTextWithOffset( -offset, 0, txt, bmp);
		copyTextWithOffset( -offset, 0, txt, bmp);
		copyTextWithOffset( 0, -offset, txt, bmp);
		
		_matrix.translate(offset, 0);
		
		txt.textColor = oldcolor;
	}
	
	private function copyTextWithOffset(x:Float, y:Float, txt:TextField, bmp:BitmapData)
	{
		_matrix.translate(x, y);
		bmp.draw(txt, _matrix);
	}
```

### PR DESCRIPTION
**Pull request by mrcdk**
Fixes #616

### CODE REVIEW

**Comment by larsiusprime** [comment]
Great!

**Comment by jgranick** [comment]
Can't we use image.dirty instead of adding an additional using framebuffer value?

**Comment by mrcdk** [comment]
it's used to get the texture from the framebuffer on `getTexture()`

**Comment by larsiusprime** [comment]
This change by itself doesn't look like it's enough:

mrcdk

**Comment by mrcdk** [comment]
@larsiusprime what happened? can you post a sample?

**Comment by larsiusprime** [comment]
Same source as 616:
https://github.com/openfl/openfl/issues/616

**Comment by mrcdk** [comment]
Uh, I'm using this code (all the code from that issue):
```haxe
package tests;
import openfl.display.Bitmap;
import openfl.display.BitmapData;
import openfl.display.Sprite;
import openfl.geom.Matrix;
import openfl.geom.Rectangle;
import openfl.text.TextField;

/**
 * ...
 * @author MrCdK
 */
class Issue616 extends Sprite
{
	
    private var _matrix:Matrix;

    public function new () {

        _matrix = new Matrix();

        super ();
        textTest();
		textTest2();
    }

    private function textTest():Void
    {
        var text:TextField = new TextField();
        addChild(text);

        text.textColor = 0xFFFF0000;
        text.text = "Hello, World!";

        text.x = 5;
        text.y = 5;

        var data = new BitmapData(Std.int(text.textWidth+4), Std.int(text.textHeight+4), true);
        var r = new Rectangle(0, 0, data.width, data.height);

        // WORKS if drawSelf = true  (text on yellow bkg)
        //!WORKS if drawSelf = false (text on !exist bkg)
        data.draw(text);
        data.fillRect(r, 0xFFFFFF00);
        data.draw(text);

        var b = new Bitmap(data);
        b.x = text.x + text.textWidth + 10;
        b.y = text.y;
        addChild(b);

        var data2 = new BitmapData(data.width, data.height, true);
        var r2 = new Rectangle(0, 0, data2.width, data2.height);

        // WORKS if drawSelf = false (text on yellow bkg)
        // WORKS if drawSelf = true  (text on yellow bkg)
        data2.fillRect(r, 0xFFFFFF00);
        data2.draw(text);

        var b2 = new Bitmap(data2);
        b2.x = b.x + b.width + 10;
        b2.y = b.y;
        addChild(b2);

        var data3 = new BitmapData(data.width, data.height, true);
        var r3 = new Rectangle(0, 0, data3.width, data3.height);

        // WORKS if drawSelf = false (yellow text outlined blue)
        //!WORKS if drawSelf = true  (yellow text)
        drawTextWithBorder(text, data3, 0xFFFFFF00, 0xFF0000FF, 1);

        var b3 = new Bitmap(data3);
        b3.x = b2.x + b2.width + 10;
        b3.y = b2.y;
        addChild(b3);
    }

    private function drawTextWithBorder(txt:TextField, bmp:BitmapData, color:Int, outlineColor:Int, border:Int)
    {
        drawOutline(txt, bmp, border, outlineColor);
        var oldcolor = txt.textColor;
        txt.textColor = color;
        bmp.draw(txt);
        txt.textColor = oldcolor;
    }

    private function drawOutline(txt:TextField, bmp:BitmapData, offset:Int, color:Int)
    {
        _matrix.identity();

        var oldcolor = txt.defaultTextFormat.color;

        txt.textColor = color;

        copyTextWithOffset( -offset, -offset, txt, bmp);
        copyTextWithOffset( offset, 0, txt, bmp);
        copyTextWithOffset( offset, 0, txt, bmp);
        copyTextWithOffset( 0, offset, txt, bmp);
        copyTextWithOffset( 0, offset, txt, bmp);
        copyTextWithOffset( -offset, 0, txt, bmp);
        copyTextWithOffset( -offset, 0, txt, bmp);
        copyTextWithOffset( 0, -offset, txt, bmp);

        _matrix.translate(offset, 0);

        txt.textColor = oldcolor;
    }

    private function copyTextWithOffset(x:Float, y:Float, txt:TextField, bmp:BitmapData)
    {
        _matrix.translate(x, y);
        bmp.draw(txt, _matrix);
    }
	
    private function textTest2():Void
    {
        var text:TextField = new TextField();
        addChild(text);

        text.textColor = 0xFFFF0000;
        text.text = "Hello, World!";

        text.x = 5;
        text.y = 5;

        var data = new BitmapData(Std.int(text.textWidth+4), Std.int(text.textHeight+4), true);
        var r = new Rectangle(0, 0, data.width, data.height);

        data.draw(text, _matrix);
        _matrix.translate(2, 2);
        data.draw(text, _matrix);

        var b = new Bitmap(data);
        b.x = text.x + text.textWidth + 10;
        b.y = text.y + 50;

        addChild(b);
		
		var b2:BitmapData = new BitmapData(10, 10, false, 0xFF0000FF);
		
		var d2 = new BitmapData(Std.int(text.textWidth+4), Std.int(text.textHeight+4), true);
		d2.draw(b2, _matrix);
		_matrix.translate(2, 2);
		d2.draw(b2, _matrix);
		
        var b = new Bitmap(d2);
        b.x = 10;
        b.y = 50;

        addChild(b);
		
		
    }
	
}
```
and this is the output I get
image

**Comment by larsiusprime** [comment]
Hmmm, let me make sure it's not a "git didn't actually update like I thought it did" bug.

**Comment by larsiusprime** [comment]
....and everything seems fine. False alarm :P

**Pull request merged**
