### PR TITLE
Added noise calculation function

### PR DESCRIPTION
**Pull request by gamepopper**
I have noticed that the functions for noise in the BitmapData class still haven't been implemented yet. I was originally approached to by Joshua Granick to write implementations for both noise and perlin noise, and this was the function that I wrote.

It takes into account the channel options and high and low colour options as well.

### CODE REVIEW

**Comment by MSGhero** [comment]
Does this have the same results as flash's implementation?

**Comment by gamepopper** [comment]
The output should be virtually identical, here's a render test using a basic OpenFL application. The left is a bitmap of 100,100 using the BitmapData's current noise function, and on the right is a bitmap of the same size using my implementation.

Test Preview

**Comment by MSGhero** [comment]
I mean as far as the exact noise function used, which is different in those two cases. In the discussion in #913, we figured we could either find and implement the exact flash function for noise and perlin, or we could just override flash's default behavior for those two functions only.

**Comment by gamepopper** [comment]
Problem I had with implementing Perlin noise was that the parameters made it much more complex. At least with this noise implementation, it also works on cpp targets (although HTML5 appears to have some issues with the setPixel32 function).

CPP Output Comparison

**Comment by MSGhero** [comment]
In that issue, someone found flash's implementation written out already, but there was some kind of issue. I don't know if it's implemented correctly in openfl legacy which is where it was tested.

Anyway, not for me to decide.

**Comment by jgranick** [comment]
This looks like a clean step forward. This is a good discussion to continue to have, regarding reproducibility and performance, but I'm going to pull since its an increment forward from a missing implementation (for sure!)

**Pull request merged**
