### PR TITLE
Speedup (dramatically) canvas BitmapData rendering in DOM

### PR DESCRIPTION
**Pull request by restorer**
Speedup (dramatically) non-image BitmapData (when __canvas is used) rendering in DOM mode

### CODE REVIEW

**Comment by jgranick** [comment]
The underlying Lime `Image` type does have a "dirty" flag, perhaps we could use that.

I see a potential problem with multiple bitmaps sharing a single `BitmapData`, perhaps what we need is to use the `image.dirty` flag to check for needing to synchronize, and then perhaps we need to have an integer value that increments every time the `BitmapData` is synch'ed, then the `Bitmap` can check if the `BitmapData` version ID matches, and if not, update it's canvas element

**Comment by restorer** [comment]
Oh, totally forgot that multiple bitmaps can share a single `BitmapData`.
Just committed a fix.

**Comment by restorer** [comment]
> The underlying Lime Image type does have a "dirty" flag, perhaps we could use that

At first attempt I also try to use "dirty" from lime, but it turned out that it is not suitable (I don't remember exact reason). That's why I added "__changeId".

**Comment by ibilon** [comment]
This is targeting the master branch,
if this still fix issues in the latest version please open a new pull request against the develop branch.

**Pull request closed without merging**
