### PR TITLE
[pls test] Text format fixes

### LINKED ISSUE #698: TextField.setTextFormat issues with subset formatting and newlines
Having trouble with `TextField.setTextFormat` when you have newlines and a subset of characters are given a different format. On Flash, the display is correct. On native legacy, the vertical spacing of the subset characters is off. And on native default, the subset formatting is applied to the entire TextField.

From left to right, native, native (`-Dlegacy`), and Flash:
bug

Code to reproduce, ran on OpenFL 3.0.8, Lime 2.4.3, and Haxe 3.2:

``` haxe
        var tf = new TextField();
        tf.embedFonts = true;
        tf.text = "hello\nbug\nnew line";

        var font = Assets.getFont("04B_03__.ttf").fontName;
        var format = new TextFormat(font, 25, 0xFFFFFF);
        var formatLarge = new TextFormat(font, 50, 0xFF0000);
        tf.setTextFormat(format);
        var bug = tf.text.indexOf("bug");
        tf.setTextFormat(formatLarge, bug, bug + 3);

        tf.width = Math.ceil(tf.textWidth + 4);
        tf.height = Math.ceil(tf.textHeight + 4);
```

### LINKED ISSUE #1657: [TextField] html tags doesn't work properly (Bounty 100EUR)
Haxe 3.4.2
Openfl 6.0.1
Lime 5.3.0

Here is a sample of code that only works perfectly on flash:

```
var texts:Array<String> = ["A<font color='#ff0000'>R</font>A",
					"B <font color='#ff0000'>R</font>B ",
					"C<font color='#ff0000'>R</font> C",
					"DD<font color='#ff0000'>R</font>D",
					"E<font color='#ff0000'>R</font>EE",
					"F<font color='#ff0000'>RRRR</font>F"];
		
		for (i in 0...texts.length)
		{
			var t:TextField = new TextField();
			t.htmlText = texts[i];
			addChild(t);
			t.y = i * 50;
		}
```
As you can see the only working field is `C<font color='#ff0000'>R</font> C` in html5 or neko. There is a space between the closing tag and the next character. In flash, all R character are red as expected.

I really want this feature fixed for html5. I offer a bounty of 100 EUR.

### PR DESCRIPTION
**Pull request by MSGhero**
Closes #1657, closes #698 

Fixes multiple formats per TextField: `textHeight`, baseline alignment, individual line heights, and some edge cases.

I've done a good few test cases, but like I found an edge case while setting up this PR that I need to fix still.

cc: @loudoweb @Misiur @scriptorum @larsiusprime @ anyone who uses text formats

### CODE REVIEW

**Comment by jgranick** [comment]
This fixes my test cases

**Comment by MSGhero** [comment]
Ok cool. I have one more edge case. The issue below is that "fantastic" should wrap due to spaces, but one of the letters is formatted. This causes the space-wrapping while loop to end prematurely.

```haxe
var tf = new TextField();
tf.text = "here is some fantastic text"; // also try "here is some fantastic\ntext"
tf.setTextFormat(new TextFormat(null, 8), 15, 16);
tf.wordWrap = true;
addChild(tf);
```

This one is a major headache, so I'm gonna pass for a while.

**Comment by loudoweb** [comment]
I've found 2 regression bugs on this PR:

### **Bug on word wrap(Major bug)** 

```
var t:TextField = new TextField();
var format = t.defaultTextFormat;
format.font = Assets.getFont('fonts/Roboto-Medium.ttf').fontName;
t.type = 'input';
t.multiline = true;
t.defaultTextFormat = format;
t.embedFonts = true;
t.htmlText = "ooo OOO OOOOOoo OOOO";
addChild(t);
t.width = 62;
t.height = 50;
t.wordWrap = true;
```
Try to write : `ooo OOO OOOOOoo OOOO`

bug on input

### **Bug on selection (cosmetic bug, really minor)**
Look at the selection (there is some vertical offset depending of the character)

bug on selection

**Comment by MSGhero** [comment]
Can you try this out when you get a chance? https://github.com/MSGhero/openfl/blob/edge-case/openfl/_internal/text/TextEngine.hx

I can't replicate the first issue, so it might be something I fixed after the PR.

I see what the issue is with the second one, so I'll do that when I get time again.

**Comment by loudoweb** [comment]
Yes the first issue is fixed! Good job!

**Comment by MSGhero** [comment]
I fixed the vertical offset in #1674, but I'm also creating an issue since I can't figure out why the 3rd "o" isn't fully covered by selection highlight.

**Pull request merged**
