### PR TITLE
Margins and indents

### LINKED ISSUE #1937: left/rightMargin not implemented
These two impact space-wrapping, long-word-wrapping, and text alignment.

Note: looks like only the format of the first character in a line is considered for doing margins

### PR DESCRIPTION
**Pull request by MSGhero**
Closes #1937, #2046 

Implements margins, indent, and blockIndent. Also cleans up some infinite loops that showed up from these changes.

### CODE REVIEW

**Comment by MSGhero** [comment]
I plan on implementing `Paragraph` and `Line` classes at some point, but I wanted to get this mostly correct PR out first

**Comment by MSGhero** [comment]
Gonna merge this soon since I haven't been having any issues on my local branch

**Comment by loudoweb** [comment]
For a full implementation, is it possible to add indent and margin in html?
Sample of htmlText with margin and indent.
`<TEXTFORMAT LEFTMARGIN="40" RIGHTMARGIN="40" INDENT="20">`

**Comment by MSGhero** [comment]
The html parser already brings those into a TextFormat object, so my guess is that already works. I haven’t tested it though, I can soon.

**Comment by MSGhero** [comment]
@loudoweb can you make a new issue if this doesn't make formats work for htmlText? I'm not in a good position to test that now

**Pull request merged**
