### PR TITLE
StageAlignment and StageScaleMode

### PR DESCRIPTION
**Pull request by mumeka**
This is an implementation for StageAlign and StageScaleMode. It works, however we need to talk some issues, there can be better approaches.

(1):
In Flash you can set:
    ```stage.align = "";```
Which makes stage centered, however this behaviour is not documented. And we can not write this line in Haxe, it tells ```stage.align must be flash.display.StageAlign```.

We use StageAlign as an Enum in Openfl, so we can write this code:
    ```stage.align = null;```
But this code crashes in Flash version, it does not allow null.
To make it centered in Flash ouput we need to remove all lines which sets ```stage.align```

(2)
In Flash stage alignment and scaleMode changes view however, it does not edit ```stage.tranform```, changes are hidden.
a
b
c

(2.A.)
Image A uses ```stage.align = StageAlign.TopLeft;```
For Flash transform is:
```stage.transform = (1, 0, 0, 1, 0, 0)```
For Native Openfl with discussed code:
```stage.transform = (1, 0, 0, 1, 0, 0)```

(2.B.)
Image B uses ```stage.align = StageAlign.BottomRight;```
For Flash transform is:
```stage.transform = (1, 0, 0, 1, 0, 0)```
For Native Openfl with discussed code:
```stage.transform = (1, 0, 0, 1, 150, 150)```

(2.C.)
Image C uses ```stage.align = StageAlign.TopLeft; stage.scaleMode = StageScaleMode.SHOW_ALL;```
For Flash transform is:
```stage.transform = (1, 0, 0, 1, 0, 0)```
For Native Openfl with discussed code:
```stage.transform = (2, 0, 0, 2, 0, 0)```

(2.Final)
So this implementation is changing transform and changes are not hidden from developer. Maybe we can hide this changes from transform matrix if it is harmful. 

I will make more tests for this pull request, just wanted to receive ideas.

### CODE REVIEW

**Comment by MSGhero** [comment]
(1) Do you think changing `StageAlign` to an `@:enum abstract(String) from String` would work here? There are some other enum classes that cause this kind of issue as well.

**Comment by mumeka** [comment]
It still says ```String should be flash.display.StageAlign``` while compiling Flash target with ```@:enum abstract StageAlign(String) from String```.

You can write ```stage.align = ""``` in native flash with Adobe Flash CC. Because ```Stage.align``` is a String.

However, while Openfl is compiling Flash target, it is not accepting ```String``` but only ```StageAlign``` enum.

**Comment by MSGhero** [comment]
The string you type in has to match the strings defined inside the abstract, and you probably don't have "" defined. Maybe try `to String` too, but I mean it's not that big of a deal.

**Comment by mumeka** [comment]
Ready for merging. We can find a way to fix mentioned issues later, this implementation is better than nothing.

**Pull request closed without merging**
