### PR TITLE
[HTML5] TextEngine fixes

### PR DESCRIPTION
**Pull request by mayakwd**
Instead of previous PR (https://github.com/openfl/openfl/pull/1282) that broke a lot of things is better to use this one.

### CODE REVIEW

**Comment by mayakwd** [comment]
@loudoweb, try this one please.

**Comment by loudoweb** [comment]
Hello. Thanks for the PR. I'm currently trying but there is something wrong somewhere (maybe this PR, maybe last Lime or Openfl, I don't know) because my project sample crashes.

**Comment by mayakwd** [comment]
I've tested on the latest openfl and lime.

**Comment by loudoweb** [comment]
Does last openfl/lime need last Haxe? I'm on Haxe 3.2.0.

**Comment by jgranick** [comment]
I test OpenFL and Lime against Haxe 3.2.1, personally

**Comment by loudoweb** [comment]
I've made further test and the reason my sample crashes is not because of this PR, it's because : 
`TextextField.htmlText` is buggy in last openfl when using html tags.

There are recent commits on TextEngine and TextField, I'm pretty sure the culprit is one them (be careful, flash works but not other targets).

**Comment by loudoweb** [comment]
If I remove this commit https://github.com/openfl/openfl/commit/d2c98111bd6c400b8757b288834eac869c8144cc everything is fine! So this the culprit.

So I've test your PR and indeed you fixed the issue https://github.com/openfl/openfl/issues/1273 without input caret regression. Good job!

**Comment by loudoweb** [comment]
Thank you!

**Comment by jgranick** [comment]
Thanks for your help, I believe both of these have been resolved :smile:

**Pull request closed without merging**
