### PR TITLE
Performance improvement, Use the queue method to update the objects that need to be updated.

### PR DESCRIPTION
**Pull request by rainyt**
Use the queue method to update the objects that need to be updated.

At present, it is known that there are rendering problems in DOM, so DOM will maintain the original implementation.

Current performance improvement needs to open definition `queue_experimental_optimization` use:

```xml
<haxedef name="queue_experimental_optimization"/>
```

### CODE REVIEW

**Comment by rainyt** [comment]
FB1ADB21AEE9FF54FF18BE693829480C
use `queue_experimental_optimization `:
F5749803EE26920D62CF0F8F92177A49

**Comment by rainyt** [comment]
Tilemap may encounter the problem of not updating in time.

**Comment by rainyt** [comment]
I have temporarily fixed the problem that tilemap rendering is not timely, but there may still be the problem that the rendering queue is not in the correct order

**Comment by rainyt** [comment]
image
Current performance reference

**Comment by rainyt** [comment]
There is a known problem that an object whose transparency is modified by actuate will not render.(resolved)

**Comment by ShaharMS** [comment]
But that shouldn't be a problem with the new update method right? It's an actuate problem

**Comment by rainyt** [comment]
When using queue update, this transformonely should always be executed

**Comment by rainyt** [comment]
> But that shouldn't be a problem with the new update method right? It's an actuate problem

I don't know, but it should work well now.

**Comment by rainyt** [comment]
image
Current performance

**Comment by rainyt** [comment]
New problem: it is easy to delay scaling when scaling. It usually only happens on mouse events.

**Comment by rainyt** [comment]
image
The problem of delayed scaling has been solved and does not seem to have much impact on performance

**Comment by rainyt** [comment]
Distress, which will affect the performance of other APIs.

**Comment by rainyt** [comment]
Now everything is normal, I will continue to test.

**Comment by rainyt** [comment]
I have tested in 2 game projects and no new problems have occurred. It is suggested that it can be merged. 
Provide this function for people in need.

**Comment by loudoweb** [comment]
I want to test this. I think I can have the time next week.

**Comment by rainyt** [comment]
> I want to test this. I think I can have the time next week.

Great, I'll wait for your good news.

**Comment by barisyild** [comment]
I've tested it on a few of my projects too, it's pretty good 👍

**Comment by rainyt** [comment]
> I want to test this. I think I can have the time next week.

I wonder if there are any results?

**Comment by loudoweb** [comment]
I still haven't had the chance to test it.

**Comment by DigiEggz** [comment]
> FB1ADB21AEE9FF54FF18BE693829480C use `queue_experimental_optimization `: F5749803EE26920D62CF0F8F92177A49

Which app do you use to test performance? I'll try this out soon!

**Comment by barisyild** [comment]
> > FB1ADB21AEE9FF54FF18BE693829480C use `queue_experimental_optimization `: F5749803EE26920D62CF0F8F92177A49
> 
> Which app do you use to test performance? I'll try this out soon!

https://www.youtube.com/watch?v=KWM5wxlDuis&ab_channel=CodemadTV

**Comment by DigiEggz** [comment]
v1

v2


My results also look promising. Thanks for your work on this, @rainyt!

**Comment by rainyt** [comment]
Improve performance `__updateQueue`

**Comment by barisyild** [comment]
@joshtynjala @Dimensionscape should consider merging this.

**Comment by barisyild** [comment]
It provides a lot of performance increase in libraries and projects with many nested containers, such as Animate Atlas and [SWF](https://github.com/openfl/swf).

I highly recommend you try my benchmark code.

without queue_experimental_optimization: 14 FPS
with queue_experimental_optimization: 40 FPS

Since the feature is enabled with define, there is no performance or behavior impact to the original method.

@joshtynjala @Dimensionscape 

```haxe
var sprite:Sprite = new Sprite();
this.addChild(sprite);
for(i in 0...100)
{
	var tempSprite:Sprite = sprite;
	sprite = new Sprite();
	for(c in 0...1000)
	{
		tempSprite.addChild(new Sprite());
	}
	tempSprite.addChild(sprite);
}

sprite.graphics.beginFill(0xFF0000);
sprite.graphics.drawRect(0, 0, 250, 250);
sprite.graphics.endFill();


this.addEventListener(Event.ENTER_FRAME, function(e:Event){
	sprite.x = Math.random() * stage.stageWidth;
	sprite.y = Math.random() * stage.stageHeight;
});
```

**Comment by joshtynjala** [comment]
Ideally, I'd like to merge this into the 9.4.0-Dev branch after we release 9.3.0 later this month.

In the meantime, I'm doing some tests to see if I can break the new code. The most likely indicators that I would expect to see if something were broken are as follows:

- a display object isn't re-rendered after something is updated, and it still looks the same as it did before
- display objects render out of order, where one appears in front of the other, but it should be behind the other
 
So far, everything seems to be working correctly, so that's great! I plan to do some additional tests today, and perhaps some more in the coming week or two, if I have time.

For reference, here is some code that I used today to see if I could get anything to render out of order (EDIT: added better code that tests more things!).

```haxe
import openfl.geom.ColorTransform;
import openfl.Lib;
import openfl.events.KeyboardEvent;
import openfl.ui.Keyboard;
import openfl.events.MouseEvent;
import openfl.display.Sprite;

class RenderQueueTest extends Sprite {
	public function new() {
		super();

		trace(#if queue_experimental_optimization "render queue optimization ON" #else "***WARNING*** render queue optimization OFF" #end);

		var stage = Lib.current.stage;

		final COLORS = [
			0xff0000,
			0x00ff00,
			0x0000ff,
			0xff7f00,
			0x7fff00,
			0x7f00ff,
			0xff007f,
			0x00ff7f,
			0x007fff
		];

		function defaultDrawSprite(sprite:Sprite, ?color:UInt):Void {
			if (color == null) {
				color = COLORS[0];
			}
			sprite.graphics.clear();
			sprite.graphics.lineStyle(4);
			sprite.graphics.beginFill(color);
			sprite.graphics.drawCircle(50.0, 50.0, 50.0);
			sprite.graphics.endFill();
		}

		function defaultCreateSprite(?color:UInt):Sprite {
			if (color == null) {
				color = COLORS[0];
			}
			var sprite = new Sprite();
			defaultDrawSprite(sprite, color);
			return sprite;
		}

		function defaultSiblingsInit(?createSprite:() -> Sprite):Array<Sprite> {
			if (createSprite == null) {
				createSprite = () -> defaultCreateSprite();
			}
			var sprites:Array<Sprite> = [];
			var currentX = 0.0;
			var currentY = 0.0;
			for (i in 0...100) {
				var sprite = createSprite();
				sprite.x = currentX;
				sprite.y = currentY;
				currentX += 60.0;
				if (currentX >= stage.stageWidth) {
					currentX = 0.0;
					currentY += 60.0;
				}
				sprites.push(sprite);
				addChild(sprite);
			}
			return sprites;
		}

		function defaultHierarchyInit(?createSprite:() -> Sprite):Array<Sprite> {
			if (createSprite == null) {
				createSprite = () -> defaultCreateSprite();
			}
			var sprites:Array<Sprite> = [];
			var currentParent:Sprite = this;
			for (i in 0...10) {
				var sprite = createSprite();
				sprite.x = 25.0;
				sprite.y = 25.0;
				sprites.push(sprite);
				currentParent.addChild(sprite);
				currentParent = sprite;
			}
			return sprites;
		}

		final MODES:Array<Mode> = [
			{
				name: "siblings: graphics clear and redraw",
				init: () -> {
					return defaultSiblingsInit(() -> new Sprite());
				},
				updateSprites: function(sprites:Array<Sprite>):Void {
					var color = COLORS[Std.int(COLORS.length * Math.random())];
					for (i in 0...sprites.length) {
						var sprite = sprites[i];
						defaultDrawSprite(sprite, color);
					}
				}
			},
			{
				name: "siblings: set scaleX and scaleY",
				init: () -> {
					return defaultSiblingsInit();
				},
				updateSprites: function(sprites:Array<Sprite>):Void {
					final SCALES = [0.9, 1.0, 1.1];
					for (i in 0...sprites.length) {
						var scale = SCALES[i % SCALES.length];
						var sprite = sprites[i];
						sprite.scaleX = scale;
						sprite.scaleY = scale;
					}
				}
			},
			{
				name: "siblings: set x and y",
				init: () -> {
					return defaultSiblingsInit();
				},
				updateSprites: function(sprites:Array<Sprite>):Void {
					var OFFSETS = [-4.0, 0.0, 4.0];
					var offsetX = OFFSETS[Std.int(OFFSETS.length * Math.random())];
					var offsetY = OFFSETS[Std.int(OFFSETS.length * Math.random())];
					for (i in 0...sprites.length) {
						var sprite = sprites[i];
						sprite.x += offsetX;
						sprite.y += offsetY;
					}
				}
			},
			{
				name: "siblings: set alpha",
				init: () -> {
					return defaultSiblingsInit();
				},
				updateSprites: function(sprites:Array<Sprite>):Void {
					// one-fourth are semi-transparent
					// this test is kind of hard to see, so I tried to limit the
					// number of transparent shapes to make it easier
					final ALPHAS = [1.0, 0.65, 1.0, 1.0];
					for (i in 0...sprites.length) {
						var alpha = ALPHAS[i % ALPHAS.length];
						var sprite = sprites[i];
						sprite.alpha = alpha;
					}
				}
			},
			{
				name: "siblings: set rotation",
				init: () -> {
					return defaultSiblingsInit();
				},
				updateSprites: function(sprites:Array<Sprite>):Void {
					final ROTATIONS = [-10.0, 0.0, 10.0];
					for (i in 0...sprites.length) {
						var rotations = ROTATIONS[i % ROTATIONS.length];
						var sprite = sprites[i];
						sprite.rotation = rotations;
					}
				}
			},
			{
				name: "siblings: set transform.colorTransform",
				init: () -> {
					return defaultSiblingsInit(() -> {
						return defaultCreateSprite(0xffffff);
					});
				},
				updateSprites: function(sprites:Array<Sprite>):Void {
					for (i in 0...sprites.length) {
						var color = COLORS[i % COLORS.length];
						var sprite = sprites[i];
						var r = (color >> 16) & 0xff;
						var g = (color >> 8) & 0xff;
						var b = color & 0xff;
						sprite.transform.colorTransform = new ColorTransform(0.5, 0.5, 0.5, 1, r, g, b);
					}
				}
			},
			{
				name: "hierarchy: graphics clear and redraw",
				init: () -> {
					return defaultHierarchyInit(() -> new Sprite());
				},
				updateSprites: function(sprites:Array<Sprite>):Void {
					for (i in 0...sprites.length) {
						var color = COLORS[i % COLORS.length];
						var sprite = sprites[i];
						defaultDrawSprite(sprite, color);
					}
				}
			},
			{
				name: "hierarchy: set scaleX and scaleY",
				init: () -> {
					return defaultHierarchyInit();
				},
				updateSprites: function(sprites:Array<Sprite>):Void {
					final SCALES = [0.9, 1.0, 1.1];
					for (i in 0...sprites.length) {
						var scale = SCALES[i % SCALES.length];
						var sprite = sprites[i];
						sprite.scaleX = scale;
						sprite.scaleY = scale;
					}
				}
			},
			{
				name: "hierarchy: set x and y",
				init: () -> {
					return defaultHierarchyInit();
				},
				updateSprites: function(sprites:Array<Sprite>):Void {
					var OFFSETS = [-4.0, 0.0, 4.0];
					var offsetX = OFFSETS[Std.int(OFFSETS.length * Math.random())];
					var offsetY = OFFSETS[Std.int(OFFSETS.length * Math.random())];
					for (i in 0...sprites.length) {
						var sprite = sprites[i];
						sprite.x += offsetX;
						sprite.y += offsetY;
					}
				}
			},
			{
				name: "hierarchy: set alpha",
				init: () -> {
					return defaultHierarchyInit();
				},
				updateSprites: function(sprites:Array<Sprite>):Void {
					final ALPHAS = [1.0, 0.85, 1.0, 1.0];
					for (i in 0...sprites.length) {
						var alpha = ALPHAS[i % ALPHAS.length];
						var sprite = sprites[i];
						sprite.alpha = alpha;
					}
				}
			},
			{
				name: "hierarchy: set rotation",
				init: () -> {
					return defaultHierarchyInit();
				},
				updateSprites: function(sprites:Array<Sprite>):Void {
					final ROTATIONS = [-10.0, 0.0, 10.0];
					for (i in 0...sprites.length) {
						var rotations = ROTATIONS[i % ROTATIONS.length];
						var sprite = sprites[i];
						sprite.rotation = rotations;
					}
				}
			},
			{
				name: "hierarchy: set transform.colorTransform",
				init: () -> {
					return defaultHierarchyInit(() -> {
						return defaultCreateSprite(0xffffff);
					});
				},
				updateSprites: function(sprites:Array<Sprite>):Void {
					for (i in 0...sprites.length) {
						var color = COLORS[i % COLORS.length];
						var sprite = sprites[i];
						var r = 0.1 * ((color >> 16) & 0xff);
						var g = 0.1 * ((color >> 8) & 0xff);
						var b = 0.1 * (color & 0xff);
						sprite.transform.colorTransform = new ColorTransform(0.75, 0.75, 0.75, 1, r, g, b);
					}
				}
			}
		];

		function shuffle(array:Array<Any>) {
			var currentIndex = array.length;
			var randomIndex = 0;
			while (currentIndex > 0) {
				randomIndex = Math.floor(Math.random() * currentIndex);
				currentIndex--;
				var temp = array[currentIndex];
				array[currentIndex] = array[randomIndex];
				array[randomIndex] = temp;
			}
		}

		var currentModeIndex:Int = 0;
		var currentMode:Mode;
		var sprites:Array<Sprite> = [];
		function applyMode(newModeIndex:Int):Void {
			while (numChildren > 0) {
				removeChildAt(0);
			}

			currentModeIndex = newModeIndex;
			// clear previous mode
			currentMode = MODES[currentModeIndex];
			trace("mode: " + currentMode.name);
			sprites = currentMode.init();
			currentMode.updateSprites(sprites);
		}

		stage.addEventListener(MouseEvent.CLICK, event -> {
			shuffle(sprites);
			currentMode.updateSprites(sprites);
		});

		stage.addEventListener(KeyboardEvent.KEY_DOWN, event -> {
			if (event.keyCode == Keyboard.RIGHT) {
				var newModeIndex = currentModeIndex + 1;
				if (newModeIndex >= MODES.length) {
					newModeIndex = 0;
				}
				applyMode(newModeIndex);
			} else if (event.keyCode == Keyboard.LEFT) {
				var newModeIndex = currentModeIndex - 1;
				if (newModeIndex < 0) {
					newModeIndex = MODES.length - 1;
				}
				applyMode(newModeIndex);
			}
		});

		trace("click stage to refresh sprites with current mode (try to do it a few times!)");
		trace("press right or left arrow key to change modes");
		applyMode(currentModeIndex);
	}
}

private typedef Mode = {
	name:String,
	init:() -> Array<Sprite>,
	updateSprites:(Array<Sprite>) -> Void
}
```

**Comment by barisyild** [comment]
> Ideally, I'd like to merge this into the 9.4.0-Dev branch after we release 9.3.0 later this month.
> 
> In the meantime, I'm doing some tests to see if I can break the new code. The most likely indicators that I would expect to see if something were broken are as follows:
> 
> * a display object isn't re-rendered after something is updated, and it still looks the same as it did before
> * display objects render out of order, where one appears in front of the other, but it should be behind the other
> 
> So far, everything seems to be working correctly, so that's great! I plan to do some additional tests today, and perhaps some more in the coming week or two, if I have time.
> 
> For reference, here is some code that I used today to see if I could get anything to render out of order (EDIT: added better code that tests more things!).
> 
> ```hx
> import openfl.geom.ColorTransform;
> import openfl.Lib;
> import openfl.events.KeyboardEvent;
> import openfl.ui.Keyboard;
> import openfl.events.MouseEvent;
> import openfl.display.Sprite;
> 
> class RenderQueueTest extends Sprite {
> 	public function new() {
> 		super();
> 
> 		trace(#if queue_experimental_optimization "render queue optimization ON" #else "***WARNING*** render queue optimization OFF" #end);
> 
> 		var stage = Lib.current.stage;
> 
> 		final COLORS = [
> 			0xff0000,
> 			0x00ff00,
> 			0x0000ff,
> 			0xff7f00,
> 			0x7fff00,
> 			0x7f00ff,
> 			0xff007f,
> 			0x00ff7f,
> 			0x007fff
> 		];
> 
> 		function defaultDrawSprite(sprite:Sprite, ?color:UInt):Void {
> 			if (color == null) {
> 				color = COLORS[0];
> 			}
> 			sprite.graphics.clear();
> 			sprite.graphics.lineStyle(4);
> 			sprite.graphics.beginFill(color);
> 			sprite.graphics.drawCircle(50.0, 50.0, 50.0);
> 			sprite.graphics.endFill();
> 		}
> 
> 		function defaultCreateSprite(?color:UInt):Sprite {
> 			if (color == null) {
> 				color = COLORS[0];
> 			}
> 			var sprite = new Sprite();
> 			defaultDrawSprite(sprite, color);
> 			return sprite;
> 		}
> 
> 		function defaultSiblingsInit(?createSprite:() -> Sprite):Array<Sprite> {
> 			if (createSprite == null) {
> 				createSprite = () -> defaultCreateSprite();
> 			}
> 			var sprites:Array<Sprite> = [];
> 			var currentX = 0.0;
> 			var currentY = 0.0;
> 			for (i in 0...100) {
> 				var sprite = createSprite();
> 				sprite.x = currentX;
> 				sprite.y = currentY;
> 				currentX += 60.0;
> 				if (currentX >= stage.stageWidth) {
> 					currentX = 0.0;
> 					currentY += 60.0;
> 				}
> 				sprites.push(sprite);
> 				addChild(sprite);
> 			}
> 			return sprites;
> 		}
> 
> 		function defaultHierarchyInit(?createSprite:() -> Sprite):Array<Sprite> {
> 			if (createSprite == null) {
> 				createSprite = () -> defaultCreateSprite();
> 			}
> 			var sprites:Array<Sprite> = [];
> 			var currentParent:Sprite = this;
> 			for (i in 0...10) {
> 				var sprite = createSprite();
> 				sprite.x = 25.0;
> 				sprite.y = 25.0;
> 				sprites.push(sprite);
> 				currentParent.addChild(sprite);
> 				currentParent = sprite;
> 			}
> 			return sprites;
> 		}
> 
> 		final MODES:Array<Mode> = [
> 			{
> 				name: "siblings: graphics clear and redraw",
> 				init: () -> {
> 					return defaultSiblingsInit(() -> new Sprite());
> 				},
> 				updateSprites: function(sprites:Array<Sprite>):Void {
> 					var color = COLORS[Std.int(COLORS.length * Math.random())];
> 					for (i in 0...sprites.length) {
> 						var sprite = sprites[i];
> 						defaultDrawSprite(sprite, color);
> 					}
> 				}
> 			},
> 			{
> 				name: "siblings: set scaleX and scaleY",
> 				init: () -> {
> 					return defaultSiblingsInit();
> 				},
> 				updateSprites: function(sprites:Array<Sprite>):Void {
> 					final SCALES = [0.9, 1.0, 1.1];
> 					for (i in 0...sprites.length) {
> 						var scale = SCALES[i % SCALES.length];
> 						var sprite = sprites[i];
> 						sprite.scaleX = scale;
> 						sprite.scaleY = scale;
> 					}
> 				}
> 			},
> 			{
> 				name: "siblings: set x and y",
> 				init: () -> {
> 					return defaultSiblingsInit();
> 				},
> 				updateSprites: function(sprites:Array<Sprite>):Void {
> 					var OFFSETS = [-4.0, 0.0, 4.0];
> 					var offsetX = OFFSETS[Std.int(OFFSETS.length * Math.random())];
> 					var offsetY = OFFSETS[Std.int(OFFSETS.length * Math.random())];
> 					for (i in 0...sprites.length) {
> 						var sprite = sprites[i];
> 						sprite.x += offsetX;
> 						sprite.y += offsetY;
> 					}
> 				}
> 			},
> 			{
> 				name: "siblings: set alpha",
> 				init: () -> {
> 					return defaultSiblingsInit();
> 				},
> 				updateSprites: function(sprites:Array<Sprite>):Void {
> 					// one-fourth are semi-transparent
> 					// this test is kind of hard to see, so I tried to limit the
> 					// number of transparent shapes to make it easier
> 					final ALPHAS = [1.0, 0.65, 1.0, 1.0];
> 					for (i in 0...sprites.length) {
> 						var alpha = ALPHAS[i % ALPHAS.length];
> 						var sprite = sprites[i];
> 						sprite.alpha = alpha;
> 					}
> 				}
> 			},
> 			{
> 				name: "siblings: set rotation",
> 				init: () -> {
> 					return defaultSiblingsInit();
> 				},
> 				updateSprites: function(sprites:Array<Sprite>):Void {
> 					final ROTATIONS = [-10.0, 0.0, 10.0];
> 					for (i in 0...sprites.length) {
> 						var rotations = ROTATIONS[i % ROTATIONS.length];
> 						var sprite = sprites[i];
> 						sprite.rotation = rotations;
> 					}
> 				}
> 			},
> 			{
> 				name: "siblings: set transform.colorTransform",
> 				init: () -> {
> 					return defaultSiblingsInit(() -> {
> 						return defaultCreateSprite(0xffffff);
> 					});
> 				},
> 				updateSprites: function(sprites:Array<Sprite>):Void {
> 					for (i in 0...sprites.length) {
> 						var color = COLORS[i % COLORS.length];
> 						var sprite = sprites[i];
> 						var r = (color >> 16) & 0xff;
> 						var g = (color >> 8) & 0xff;
> 						var b = color & 0xff;
> 						sprite.transform.colorTransform = new ColorTransform(0.5, 0.5, 0.5, 1, r, g, b);
> 					}
> 				}
> 			},
> 			{
> 				name: "hierarchy: graphics clear and redraw",
> 				init: () -> {
> 					return defaultHierarchyInit(() -> new Sprite());
> 				},
> 				updateSprites: function(sprites:Array<Sprite>):Void {
> 					for (i in 0...sprites.length) {
> 						var color = COLORS[i % COLORS.length];
> 						var sprite = sprites[i];
> 						defaultDrawSprite(sprite, color);
> 					}
> 				}
> 			},
> 			{
> 				name: "hierarchy: set scaleX and scaleY",
> 				init: () -> {
> 					return defaultHierarchyInit();
> 				},
> 				updateSprites: function(sprites:Array<Sprite>):Void {
> 					final SCALES = [0.9, 1.0, 1.1];
> 					for (i in 0...sprites.length) {
> 						var scale = SCALES[i % SCALES.length];
> 						var sprite = sprites[i];
> 						sprite.scaleX = scale;
> 						sprite.scaleY = scale;
> 					}
> 				}
> 			},
> 			{
> 				name: "hierarchy: set x and y",
> 				init: () -> {
> 					return defaultHierarchyInit();
> 				},
> 				updateSprites: function(sprites:Array<Sprite>):Void {
> 					var OFFSETS = [-4.0, 0.0, 4.0];
> 					var offsetX = OFFSETS[Std.int(OFFSETS.length * Math.random())];
> 					var offsetY = OFFSETS[Std.int(OFFSETS.length * Math.random())];
> 					for (i in 0...sprites.length) {
> 						var sprite = sprites[i];
> 						sprite.x += offsetX;
> 						sprite.y += offsetY;
> 					}
> 				}
> 			},
> 			{
> 				name: "hierarchy: set alpha",
> 				init: () -> {
> 					return defaultHierarchyInit();
> 				},
> 				updateSprites: function(sprites:Array<Sprite>):Void {
> 					final ALPHAS = [1.0, 0.85, 1.0, 1.0];
> 					for (i in 0...sprites.length) {
> 						var alpha = ALPHAS[i % ALPHAS.length];
> 						var sprite = sprites[i];
> 						sprite.alpha = alpha;
> 					}
> 				}
> 			},
> 			{
> 				name: "hierarchy: set rotation",
> 				init: () -> {
> 					return defaultHierarchyInit();
> 				},
> 				updateSprites: function(sprites:Array<Sprite>):Void {
> 					final ROTATIONS = [-10.0, 0.0, 10.0];
> 					for (i in 0...sprites.length) {
> 						var rotations = ROTATIONS[i % ROTATIONS.length];
> 						var sprite = sprites[i];
> 						sprite.rotation = rotations;
> 					}
> 				}
> 			},
> 			{
> 				name: "hierarchy: set transform.colorTransform",
> 				init: () -> {
> 					return defaultHierarchyInit(() -> {
> 						return defaultCreateSprite(0xffffff);
> 					});
> 				},
> 				updateSprites: function(sprites:Array<Sprite>):Void {
> 					for (i in 0...sprites.length) {
> 						var color = COLORS[i % COLORS.length];
> 						var sprite = sprites[i];
> 						var r = 0.1 * ((color >> 16) & 0xff);
> 						var g = 0.1 * ((color >> 8) & 0xff);
> 						var b = 0.1 * (color & 0xff);
> 						sprite.transform.colorTransform = new ColorTransform(0.75, 0.75, 0.75, 1, r, g, b);
> 					}
> 				}
> 			}
> 		];
> 
> 		function shuffle(array:Array<Any>) {
> 			var currentIndex = array.length;
> 			var randomIndex = 0;
> 			while (currentIndex > 0) {
> 				randomIndex = Math.floor(Math.random() * currentIndex);
> 				currentIndex--;
> 				var temp = array[currentIndex];
> 				array[currentIndex] = array[randomIndex];
> 				array[randomIndex] = temp;
> 			}
> 		}
> 
> 		var currentModeIndex:Int = 0;
> 		var currentMode:Mode;
> 		var sprites:Array<Sprite> = [];
> 		function applyMode(newModeIndex:Int):Void {
> 			while (numChildren > 0) {
> 				removeChildAt(0);
> 			}
> 
> 			currentModeIndex = newModeIndex;
> 			// clear previous mode
> 			currentMode = MODES[currentModeIndex];
> 			trace("mode: " + currentMode.name);
> 			sprites = currentMode.init();
> 			currentMode.updateSprites(sprites);
> 		}
> 
> 		stage.addEventListener(MouseEvent.CLICK, event -> {
> 			shuffle(sprites);
> 			currentMode.updateSprites(sprites);
> 		});
> 
> 		stage.addEventListener(KeyboardEvent.KEY_DOWN, event -> {
> 			if (event.keyCode == Keyboard.RIGHT) {
> 				var newModeIndex = currentModeIndex + 1;
> 				if (newModeIndex >= MODES.length) {
> 					newModeIndex = 0;
> 				}
> 				applyMode(newModeIndex);
> 			} else if (event.keyCode == Keyboard.LEFT) {
> 				var newModeIndex = currentModeIndex - 1;
> 				if (newModeIndex < 0) {
> 					newModeIndex = MODES.length - 1;
> 				}
> 				applyMode(newModeIndex);
> 			}
> 		});
> 
> 		trace("click stage to refresh sprites with current mode (try to do it a few times!)");
> 		trace("press right or left arrow key to change modes");
> 		applyMode(currentModeIndex);
> 	}
> }
> 
> private typedef Mode = {
> 	name:String,
> 	init:() -> Array<Sprite>,
> 	updateSprites:(Array<Sprite>) -> Void
> }
> ```

This optimization dates back exactly 3 years and I have subjected it to many tests during these 3 years and there seems to be no problem.

https://github.com/barisyild/fastfl/commit/e219d946aa562c32c779355d7bb84fd5008bbab0

**Comment by barisyild** [comment]
The container that needs to be updated is also updated in the container below it, thus eliminating the possibility of many issues.

**Comment by joshtynjala** [comment]
This is merged into the 9.4.0-Dev branch. I have renamed the define to `openfl_enable_experimental_update_queue` to better match our naming convention. I also made a few small naming/optimization tweaks that don't affect behavior.

**Pull request merged**
