### PR TITLE
contentType bug fix

### PR DESCRIPTION
**Pull request by hpgood**
request.contentType bug fix

### CODE REVIEW

**Comment by ibilon** [comment]
The second comparison should probably be changed to `== ""` instead of `!=`.

**Comment by hpgood** [comment]
you are right. 

https://github.com/openfl/openfl/pull/1030

**Comment by MSGhero** [comment]
You can make changes, and the pull request will update with those changes automatically. You don't have to make a new pull :)

**Comment by hpgood** [comment]
sorry, i change code in the fellow url now.it is right ?

https://github.com/hpgood/openfl/blob/patch-3/openfl/display/Loader.hx

**Pull request closed without merging**
