### PR TITLE
added "headerOnly" parameter to Assets.getBitmapData(). Only works wi…

### PR DESCRIPTION
**Pull request by larsiusprime**
…th PNG at the moment.

### CODE REVIEW

**Comment by MSGhero** [comment]
What does header only do?, and you left a trace in there.

**Comment by larsiusprime** [comment]
Basically, there are times when you might want to know the width/height (and other metadata) about an image without having to load the whole thing into memory first. This is the foundation for that sort of feature (I expect Joshua to move the API around rather than pull this in directly)

**Comment by MSGhero** [comment]
Isn't the image already in memory, or does cpp/whatever target handle that differently than flash?

**Comment by larsiusprime** [comment]
Yes, cpp handles it differently. It loads the image from the file system on
demand.

On Thu, Jun 11, 2015 at 7:56 PM, Nick <notifications@github.com> wrote:

> Isn't the image already in memory, or does cpp/whatever target handle that
> differently than flash?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfl/openfl/pull/710#issuecomment-111317774>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by jgranick** [comment]
Thanks! Solved this with a Lime API, here:

https://github.com/openfl/lime/pull/474

**Pull request closed without merging**
