### PR TITLE
Fix: cubicCurveTo boundaries

### PR DESCRIPTION
**Pull request by m8mike**
Fixed issue #2358.
Fixed errors and completely rewritten cubicCurveTo function.
Before:
test2
After:
test1
Test code:
[Main.txt](https://github.com/openfl/openfl/files/10411628/Main.txt)

### CODE REVIEW

**Comment by joshtynjala** [comment]
Thanks! I quickly applied the first commit (93ddcf237e3982eee8cb3121e2171613d23dc23c) because using `__positionX` there was obviously wrong. At a later time, when I or another contributor have a little more time, will evaluate the rest of the commits and merge if everything looks good.

**Comment by m8mike** [comment]
[e0b5bc3](https://github.com/openfl/openfl/pull/2611/commits/e0b5bc3e917655d45a9d25571bfc71c2a9702bb5) still needs to be evaluated and merged, because it fixes the bugs with bounding boxes of cubic curves.

Here is some information on what was changed and why:

- There were 2 separate blocks calculating min and max values of x and y. I've made a function findExtrema to avoid duplication.
- u, v and w variables were renamed as a, b and c, because that's the conventional way of solving a quadratic equation.
- I've added checks for when it's division by zero and taking a square root of a negative value.
- We are searching for a min and max values across all solutions plus the first point and the last point of the curve.
- Reduced unnecessary calls of __inflateBounds. Now it is called for the top left and the bottom right corners only.

**Comment by joshtynjala** [comment]
Thanks for the detailed explanation, and for the code that I requested in #2610. We haven't forgotten about this. However, as most of us work on OpenFL when we have free time, it may take a bit before we have time to properly evaluate it.

**Comment by joshtynjala** [comment]
Adding a version of the code that draws everything to the same `graphics`.

```haxe
function addLine(p1:Point, p2:Point) {
	graphics.lineStyle(1, 0x800080);
	graphics.moveTo(p1.x, p1.y);
	graphics.lineTo(p2.x, p2.y);
	graphics.endFill();
}
function addPoint(p:Point) {
	graphics.beginFill(0xff0000);
	graphics.drawCircle(p.x, p.y, 2);
	graphics.endFill();
}
function addHandlers(p1:Point, p2:Point, p3:Point, p4:Point) {
	addLine(p1, p2);
	addLine(p3, p4);
	addPoint(p1);
	addPoint(p2);
	addPoint(p3);
	addPoint(p4);
}
function addCurve(p1:Point, p2:Point, p3:Point, p4:Point) {
	graphics.lineStyle(20, 0xff8000);
	graphics.beginFill(0xbbbbbb);
	graphics.moveTo(p1.x, p1.y);
	graphics.cubicCurveTo(p2.x, p2.y, p3.x, p3.y, p4.x, p4.y);
	graphics.endFill();
	addHandlers(p1, p2, p3, p4);
}
````

The original curves, same as before:

```haxe
addCurve(new Point(470, 310), new Point(495, 200), new Point(545, 200), new Point(570, 310));
addCurve(new Point(470, 340), new Point(495, 450), new Point(545, 450), new Point(570, 340));
addCurve(new Point(460, 120), new Point(569, 133), new Point(569, 157), new Point(460, 195));
addCurve(new Point(710, 120), new Point(600, 133), new Point(600, 157), new Point(710, 195));
addCurve(new Point(651, 458), new Point(477, 493), new Point(394, 571), new Point(270, 503));
addCurve(new Point(639, 225), new Point(681, 195), new Point(685, 254), new Point(689, 283));
addCurve(new Point(215, 326), new Point(299, 417), new Point(306, 272), new Point(317, 213));
addCurve(new Point(345, 137), new Point(371, 218), new Point(428, 193), new Point(385, 104));
addCurve(new Point(50, 100), new Point(100, 50), new Point(198, 80), new Point(298.04, 100));
```

Some new code that draws one curve, but animates the control points in an enterFrame listener:

```haxe
final distance = 500.0;
var current = 0.0;
addEventListener(Event.ENTER_FRAME, event -> {
	graphics.clear();
	current += 0.05;
	var sinValue = distance * Math.sin(current);
	var cosValue = distance * Math.cos(current);
	addCurve(new Point(300.0, 450.0), new Point(300.0 + sinValue, 250.0 + cosValue), new Point(500.0 - cosValue, 250.0 - sinValue),
		new Point(500.0, 450.0));
});
```

Same animation, but the start and end points are vertical instead of horizontal:

```haxe
final distance = 500.0;
var current = 0.0;
addEventListener(Event.ENTER_FRAME, event -> {
	graphics.clear();
	current += 0.05;
	var sinValue = distance * Math.sin(current);
	var cosValue = distance * Math.cos(current);
	addCurve(new Point(400.0, 200.0), new Point(200.0 + sinValue, 200.0 + cosValue), new Point(200.0 - cosValue, 400.0 - sinValue),
				new Point(400.0, 400.0));
});
```

**Comment by joshtynjala** [comment]
And some code that draws the curve without the control points and lines, but draws the bounds instead:

```haxe
function addBounds() {
	graphics.beginFill(0x00ff00, 0.25);
	var bounds = getBounds(this);
	graphics.drawRect(bounds.x, bounds.y, bounds.width, bounds.height);
	graphics.endFill();
}
function addCurve(p1:Point, p2:Point, p3:Point, p4:Point) {
	graphics.lineStyle(20, 0xff8000);
	graphics.beginFill(0xbbbbbb);
	graphics.moveTo(p1.x, p1.y);
	graphics.cubicCurveTo(p2.x, p2.y, p3.x, p3.y, p4.x, p4.y);
	graphics.endFill();
	addBounds();
}
```

**Pull request closed without merging**
