### PR TITLE
Made canvas renderer more consistent with Flash

### PR DESCRIPTION
**Pull request by tocsick**
This commit makes the rendering to canvas a lot more consistent with Flash. See example: http://i.imgur.com/EhkQk68.png 

I started doing this to fix issue #559 but kept going to make it as consistent as possible. Specifically, if no fill is set it won't close paths but also now you can change line style between lineTo commands and have it mirror that of Flash.

### CODE REVIEW

**Comment by tocsick** [comment]
Also fixes #420

**Comment by jgranick** [comment]
Looking at your example image, the changes look great. I just tried with a project I'm working with here, and I noticed that the renderer changes do not seem to handle holes inside of fills. For example, when using static SWF text (which comes through as shape commands), "o", "p" and other letters with a hole in the center look filled-in. For some reason, some circular masks I have aren't working properly either.

Are you set up with the SWF library? Would it be hard to try putting some static text in a SWF and reproduce what I'm talking about?

**Comment by tocsick** [comment]
Thanks for testing, I'll have a look later on today and see if I can reproduce / fix the issue.

**Comment by Hasufel** [comment]
@tocsick do you still have the haxe code of the test drawing you mirrored there in png by any chance? If so, could you post it somewhere please?

**Comment by tocsick** [comment]
@Hasufel Sure, it just grabbed snippets from the Internet it's not a comprehensive test or anything...

https://gist.github.com/tocsick/0d5c3fe1a4c928d95feb

**Comment by Hasufel** [comment]
@tocsick thank you. It's perfect as a simple reference test for shape/drawing consistency across new platforms.

**Comment by tocsick** [comment]
@jgranick Okay reproduced the issue and located the problem. See: http://i.imgur.com/tjkI4Pp.png

Rebased and squashed.

**Comment by jgranick** [comment]
Awesome, looks fine here, definitely looks better by your example, we can use this and continue to make improvements if we see anything else. Thanks! :+1:

**Comment by tocsick** [comment]
#420 and #559 can be closed :)

**Comment by jgranick** [comment]
@tocsick Is there any chance you might be interested in helping look at the Cairo software renderer? It works a lot like canvas (many browsers use Cairo under the hood, makes sense!) and in your test above, I have already gotten consistent results with Flash.

Cairo can be used on all the native platforms, so it means that we could have a renderer that's consistent with HTML5 and Flash in those places, we could then mix with the GL renderer to balance quality and performance

Let me know :smile:

**Comment by tocsick** [comment]
I'd love to help. What's the current status and how can I get involved?

**Comment by jgranick** [comment]
Lime has almost complete bindings to the Cairo library. This means we can write code against it, without touching C++. For example, this should look familiar:

https://github.com/openfl/openfl/blob/master/openfl/_internal/renderer/cairo/CairoGraphics.hx

If you use the latest Lime and OpenFL (or both from the source), you can use `openfl test neko --window-hardware=false` to force software, and use Cairo instead of OpenGL.

## Current Status

Using your gist, Cairo looks better (!) than Flash Player in the rounded rectangle, the rest is identical. In practice, it's not quite perfect, but I'm confident it can work. Mozilla, Webkit, even the Linux Flash Player use Cairo.

I bet we could use Cairo for Graphics rendering, then later hook that to a GL texture -- bitmapData.draw, (possibly) cacheAsBitmap, and non-hardware blend modes could all go through Cairo. Consistency in rendering between Flash, HTML5 (which already is quite great now!) and native would be awesome -- and really doors for Flash IDE integration, and continuing to push the envelope.

## What Works

Shapes, Bitmaps, scrollRects and masks (mostly) a lot of the Graphics API and DisplayObjectContainers seem to work

## What Doesn't

bitmapFills don't seem right, drawTiles or drawTriangles is probably related. The position on scaling a scrollRect object is off

The Graphics class is mostly there, but in some edge cases, it seems like the paths get a little narrow?

I think Canvas is implemented using Cairo in a few places, so using it seems naturally similar to the HTML5 Canvas API, with a few differences.

**Comment by jgranick** [comment]
Oh, and if you aren't on Slack chat, would be happy to talk more there if you like :smile:

**Comment by tocsick** [comment]
Cairo is awesome! Love the idea of using it for graphics rendering with the OpenGL renderer. 

I've got the Cairo renderer working pretty consistent with bitmap fills and strokes as well as gradient fills and strokes now. Check it out: http://i.imgur.com/MUh4i8D.png

I'm going to build a comprehensive graphics test pattern now to try and cover more cases. I will post it here for everyone when I'm done. Do you want me to start a new issue for the Cairo renderer?

Never used Slack chat before, how do I get on board?

**Pull request merged**
