### PR TITLE
Decomposing and recomposing of Matrix like AS3

### PR DESCRIPTION
**Pull request by dimanux**
This pull request is like https://github.com/openfl/lime/pull/315 but for new version of OpenFL

### CODE REVIEW

**Comment by jgranick** [comment]
Does anyone have a sample that helps show what is currently broken that this fixes? I'm a little scared this might hurt other behaviors :)

**Comment by starburst997** [comment]
```
package;

import openfl.display.Bitmap;
import openfl.display.Sprite;
import openfl.geom.Matrix;
import openfl.Lib;

class Main extends Sprite 
{

	public function new() 
	{
		super();
		
		// Assets:
		var bitmap1 = new Bitmap( openfl.Assets.getBitmapData("img/face.png") );
		var bitmap2 = new Bitmap( openfl.Assets.getBitmapData("img/face.png") );
		
		var matrix = new Matrix();
		matrix.scale( -1, 1 );
		bitmap1.transform.matrix = matrix;
		
		bitmap2.x = bitmap1.x = bitmap1.bitmapData.width;
		bitmap2.y = bitmap1.y = bitmap1.bitmapData.height;
		
		addChild( bitmap1 );
		addChild( bitmap2 );
	}
}
```
Expected result (flash):
matrix1

HTML5: 
matrix2

With dimanux fix:
matrixgood

**Comment by starburst997** [comment]
Also looking at @dimanux  repos there seems to have tests already done to makes sure matrix works as expected: https://github.com/dimanux/MatrixTest

**Comment by jgranick** [comment]
I just confirmed this is working now :smile:

**Pull request closed without merging**
