### PR TITLE
Fix issue #643

### LINKED ISSUE #643: Next graphics - Linestyle with alpha renders the wrong color (OpenFLNextShapeTest #1)
Test case: https://github.com/jcward/OpenFLNextShapeTest

Linestyle with alpha = 0.5 is the wrong color in Next, both the red rectangle and the green circle

[](https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/compare.png)

### PR DESCRIPTION
**Pull request by mrcdk**
Fixed the line color alpha.
Implemented basic scrollRect support on next (it doesn't support rotation on opengl) and fixed the scrollRect on HTML5 (canvas)

Fixes #643

### CODE REVIEW

**Comment by mrcdk** [comment]
Nevermind, There are still problems :disappointed:

**Comment by mrcdk** [comment]
ok, I think that solves the problems.

**Comment by jgranick** [comment]
What case does this resolve for HTML5 canvas?

**Comment by mrcdk** [comment]
When the object is scaled. https://dl.dropboxusercontent.com/u/23209045/scrollrect.mp4
Rotation is broken on html5 too (it rotates the other way around). 
Rotation won't be supported for now on neko/cpp, maybe later.

**Pull request merged**
