### PR TITLE
Apply ColorTransform directly when rendering text and shapes

### PR DESCRIPTION
**Pull request by vizanto**
This patch refactors and de-duplicates code in the Cairo and Canvas rendering classes and implements the application of color transforms to TextFields and (Shape) Graphics.

Luckily worldColorTransform was already implemented so it turned out to be fairly straightforward :-)

It introduces 2 new macros to ColorTransform that help calculate the RGBA values without temporary allocations. If and when Haxe supports multiple inline return values, these could be rewritten. Hopefully you'll find these readable enough... :)

Drawing Bitmaps with ColorTransform is untested and not implemented by this patch.

### CODE REVIEW

**Comment by vizanto** [comment]
Added some ColorTransforms to [my little test program here](https://github.com/vizanto/openfl-linestyle-bug/tree/colortransform)

Before this patch, the ColorTransforms change nothing on targets other than Flash.

**Comment by vizanto** [comment]
I just discovered that changing the `colorTransform` after rendering, doesn't invalidate the Graphics and the display is not updated. Working on that now...

**Comment by vizanto** [comment]
Discovered a copy-pasta error in `CanvasGraphics.render`.  Rebased the proper commit.

**Comment by mtari** [comment]
I have tested your changes and discovered one issue. Drawing a line isn't working, but drawing other shapes seems to work fine.

Example code:
var line = new Sprite ();
line.graphics.lineStyle (10, 0x24AFC4);
line.graphics.moveTo (10, 0);
line.graphics.lineTo (755, 0);
addChild (line);

**Comment by vizanto** [comment]
Reopened as https://github.com/openfl/openfl/pull/1251 because I keep pushing to this branch :/ 
Sorry.

**Pull request closed without merging**
