### PR TITLE
Fix BitmapData.paletteMap

### PR DESCRIPTION
**Pull request by azrafe7**
openfl [next] only

This PR changes the logic inside `BitmapData.paletteMap()` to more closely follow as3 behaviour. Namely:
- use pixels from `sourceBitmapData`
- sum values from mapping arrays to compute the resulting color

### CODE REVIEW

**Comment by azrafe7** [comment]
I've adapted code from http://www.splashdust.net/2009/11/bitmapdata-and-palettemap/ to test differences between targets, and used the flash docs to find out how to (hopefully) correctly implement it.

I'd also add that, while the loop is now simplified and a tiny bit faster, the gap in performance with flash is still huge.

I think we need a fast way to access the raw bytes cross-platform for this kind of tricks/effects to be usable in real time. Not sure how to achieve/abstract that (pixel formats, byte buffers, etc.), but would be interested to hear some ideas about this.

The gist is at https://gist.github.com/azrafe7/549ac5e8f1afccd491a7

**Comment by larsiusprime** [comment]
If you want to implement a "fast" version of this you'll probably need to dip down to the CFFI layer... but maybe there is a haxe-level fast direct bytes method available now.

@jgranick or @jcward would know.

**Comment by azrafe7** [comment]
@larsiusprime: Thanks for the quick response.

Going through CFFI would probably work for cpp|neko, but not for html5 (where it seems that `setPixels` is slower than multiple `setPixel` f.e.). Furthermore there's endianness and pixel format issues to take into account I think (not mentioning canvas/webgl/etc.).

Anyway keep the discussion going, as I'd really like to help in improving OpenFl performance regarding pixel manipulation.

**Comment by larsiusprime** [comment]
NP, sorry I don't know about how to do cross platform fast bytes right off the top of my head... I've implemented a few of these BitmapData functions myself in the past, and it would be swell if there was a fast way to access byte data.

**Comment by azrafe7** [comment]
Yes, I seem to remember you implemented `threshold()` (right?), and back then using `Memory` gave impressive results. It seems to not be the case anymore nowadays though, so still eager to find out ways to improve the status quo.

**Comment by larsiusprime** [comment]
That was way back, yeah, on the legacy codebase, and it was only effective for c++. But we're supposed to have native arrays or something like that now, and a lot of work has been done on byte-level access so maybe an API exists now.

**Comment by jcward** [comment]
> NP, sorry I don't know about how to do cross platform fast bytes right off the top of my head...
> But we're supposed to have native arrays or something like that now, and a lot of work has been done on byte-level access so maybe an API exists now.
I don't know either, but I'm interested, for sure!

**Comment by azrafe7** [comment]
@jgranick: this PR could be _slightly_ improved (performance-wise) by accessing bytes directly (i.e. instead of using wrappers, and leveraging conditional compilation), but I'm not sure about endianness as I can only test on win7.

What are your thoughts about this? Is it mergeable as it is?

**Comment by azrafe7** [comment]
I know OpenFl goes through quite a few hoops to give a common interface for bitmap features, but for reference here's a [pure haxejs implementation](http://try.haxe.org/#AFD05) to test agains the gist for html5.

PS: I'm not trying to devalue your work (not at all!), just willing to give feedback and maybe lend a hand, if I'm able to!

**Comment by ibilon** [comment]
This is targeting the master branch,
if this still fix issues in the latest version please open a new pull request against the develop branch.

**Pull request merged**
