### PR TITLE
Fix bounds calculations and scrollRect position.

### PR DESCRIPTION
**Pull request by mrcdk**
Only tested with OpenGL (windows, neko and webGL) and HTML5 canvas, other targets may need modifications.

```
FLASH
 Before moving child
 	Parent data: (w, h, bounds),512,512,(x=0, y=0, w=512, h=512)
 	Child  data: (w, h, bounds),512,512,(x=0, y=0, w=512, h=512)
 After moving child
 	Parent data: (w, h, bounds),512,512,(x=0, y=0, w=512, h=512)
 	Child  data: (w, h, bounds),512,512,(x=0, y=0, w=512, h=512)

BEFORE
 Before moving child
 	Parent data: (w, h, bounds),512,512,{ width => 512, x => 0, y => 0, height => 512 }
 	Child  data: (w, h, bounds),512,512,{ width => 512, x => 0, y => 0, height => 512 }
 After moving child
 	Parent data: (w, h, bounds),512,512,{ width => 512, x => 0, y => 0, height => 512 }
 	Child  data: (w, h, bounds),512,512,{ width => 512, x => 412, y => 412, height => 512 }

AFTER
 Before moving child
 	Parent data: (w, h, bounds),512,512,{ width => 512, x => 0, y => 0, height => 512 }
 	Child  data: (w, h, bounds),512,512,{ width => 512, x => 0, y => 0, height => 512 }
 After moving child
 	Parent data: (w, h, bounds),512,512,{ width => 512, x => 0, y => 0, height => 512 }
 	Child  data: (w, h, bounds),512,512,{ width => 512, x => 0, y => 0, height => 512 }

LEGACY
 Before moving child
 	Parent data: (w, h, bounds),512,512,(x=0, y=0, width=0, height=0)
 	Child  data: (w, h, bounds),512,512,(x=0, y=0, width=0, height=0)
 After moving child
 	Parent data: (w, h, bounds),512,512,(x=0, y=0, width=0, height=0)
 	Child  data: (w, h, bounds),512,512,(x=0, y=0, width=0, height=0)
```

---
	parent.rotation = 10; parent.scaleX = 1.2;
	
```
FLASH
 Before moving child
 	Parent data: (w, h, bounds),693.95,610.9,(x=0, y=0, w=512, h=512)
 	Child  data: (w, h, bounds),512,512,(x=0, y=0, w=512, h=512)
 After moving child
 	Parent data: (w, h, bounds),693.95,610.9,(x=0, y=0, w=512, h=512)
 	Child  data: (w, h, bounds),512,512,(x=0, y=0, w=512, h=512)

BEFORE
 Before moving child
 	Parent data: (w, h, bounds),614.4,512,{ width => 693.973750416169, x => -88.9078669654683, y => 0, height => 610.911009900812 }
 	Child  data: (w, h, bounds),512,512,{ width => 512, x => 0, y => 0, height => 512 }
 After moving child
 	Parent data: (w, h, bounds),614.4,512,{ width => 693.973750416169, x => -88.9078669654683, y => 0, height => 610.911009900812 }
 	Child  data: (w, h, bounds),512,512,{ width => 512, x => 514.4, y => 412, height => 512 }

AFTER
 Before moving child
 	Parent data: (w, h, bounds),693.973750416169,610.911009900812,{ width => 512, x => 0, y => 0, height => 512 }
 	Child  data: (w, h, bounds),512,512,{ width => 512, x => 0, y => 0, height => 512 }
 After moving child
 	Parent data: (w, h, bounds),693.973750416169,610.911009900812,{ width => 512, x => 0, y => 0, height => 512 }
 	Child  data: (w, h, bounds),512,512,{ width => 512, x => 0, y => 0, height => 512 }

LEGACY
 Before moving child
 	Parent data: (w, h, bounds),693.973754882813,610.911010742188,(x=0, y=0, width=0, height=0)
 	Child  data: (w, h, bounds),512,512,(x=0, y=0, width=0, height=0)
 After moving child
 	Parent data: (w, h, bounds),693.973754882813,610.911010742188,(x=0, y=0, width=0, height=0)
 	Child  data: (w, h, bounds),512,512,(x=0, y=0, width=0, height=0)
```
---
	parent.rotation = 10; parent.scaleX = 1.2;

```
FLASH
 Before moving child
 	Parent data: (w, h, bounds),693.95,610.9,(x=0, y=0, w=512, h=512)
 	Child  data: (w, h, bounds),512,512,(x=0, y=0, w=512, h=512)
 After moving child
 	Parent data: (w, h, bounds),1285.65,1359.65,(x=0, y=0, w=1105.95, h=1146.65)
 	Child  data: (w, h, bounds),512,512,(x=0, y=0, w=512, h=512)

BEFORE
 Before moving child
 	Parent data: (w, h, bounds),614.4,512,{ width => 693.973750416169, x => -88.9078669654683, y => 0, height => 610.911009900812 }
 	Child  data: (w, h, bounds),512,512,{ width => 693.973750416169, x => -88.9078669654683, y => 0, height => 610.911009900812 }
 After moving child
 	Parent data: (w, h, bounds),1231.68,924,{ width => 1230.33283099677, x => -88.9078669654683, y => 0, height => 1123.84135125209 }
 	Child  data: (w, h, bounds),512,512,{ width => 693.973750416169, x => 447.451213615132, y => 512.930341351273, height => 610.911009900812 }

AFTER
 Before moving child
 	Parent data: (w, h, bounds),693.973750416169,610.911009900812,{ width => 512, x => 0, y => 0, height => 512 }
 	Child  data: (w, h, bounds),512,512,{ width => 512, x => 0, y => 0, height => 512 }
 After moving child
 	Parent data: (w, h, bounds),1285.70232986588,1359.72167710996,{ width => 1105.97375041617, x => 0, y => 0, height => 1146.68196111092 }
 	Child  data: (w, h, bounds),512,512,{ width => 512, x => 0, y => 0, height => 512 }

LEGACY
 Before moving child
 	Parent data: (w, h, bounds),693.973754882813,610.911010742188,(x=0, y=0, width=0, height=0)
 	Child  data: (w, h, bounds),512,512,(x=0, y=0, width=0, height=0)
 After moving child
 	Parent data: (w, h, bounds),1285.70239257813,1359.7216796875,(x=0, y=0, width=0, height=0)
 	Child  data: (w, h, bounds),512,511.999938964844,(x=0, y=0, width=0, height=0)
```
example test 3
---
	parent.rotation = 10; parent.scaleX = 1.2;
	child.scaleX = 0.5;

```
FLASH
 Before moving child
 	Parent data: (w, h, bounds),693.95,610.9,(x=0, y=0, w=512, h=512)
 	Child  data: (w, h, bounds),256,512,(x=0, y=0, w=512, h=512)
 After moving child
 	Parent data: (w, h, bounds),992.4,1253.8,(x=0, y=0, w=849.95, h=1093.3)
 	Child  data: (w, h, bounds),256,512,(x=0, y=0, w=512, h=512)

BEFORE
 Before moving child
 	Parent data: (w, h, bounds),614.4,512,{ width => 693.973750416169, x => -88.9078669654683, y => 0, height => 610.911009900812 }
 	Child  data: (w, h, bounds),256,512,{ width => 391.440808690819, x => -88.9078669654683, y => 0, height => 557.566289721531 }
 After moving child
 	Parent data: (w, h, bounds),924.48,924,{ width => 927.799889271419, x => -88.9078669654683, y => 0, height => 1070.4966310728 }
 	Child  data: (w, h, bounds),256,512,{ width => 391.440808690819, x => 447.451213615132, y => 512.930341351273, height => 557.566289721531 }

AFTER
 Before moving child
 	Parent data: (w, h, bounds),693.973750416169,610.911009900812,{ width => 512, x => 0, y => 0, height => 512 }
 	Child  data: (w, h, bounds),256,512,{ width => 512, x => 0, y => 0, height => 512 }
 After moving child
 	Parent data: (w, h, bounds),992.432601587815,1253.84266291585,{ width => 849.973750416169, x => 0, y => 0, height => 1093.33724093164 }
 	Child  data: (w, h, bounds),256,512,{ width => 512, x => 0, y => 0, height => 512 }

LEGACY
 Before moving child
 	Parent data: (w, h, bounds),693.973754882813,610.911010742188,(x=0, y=0, width=0, height=0)
 	Child  data: (w, h, bounds),256,512,(x=0, y=0, width=0, height=0)
 After moving child
 	Parent data: (w, h, bounds),992.4326171875,1253.84265136719,(x=0, y=0, width=0, height=0)
 	Child  data: (w, h, bounds),256,511.999938964844,(x=0, y=0, width=0, height=0)
 ```
 example test 4

 ---

The source code:
```haxe
	public function new() {
		super();
		addEventListener(Event.ADDED_TO_STAGE, init);
	}
	
	function init(_) {
		var bd1 = Assets.getBitmapData("assets/openfl.png", false);
		var bd2 = Assets.getBitmapData("assets/openfl.png", false);
		bd2.colorTransform(bd2.rect, new ColorTransform(1, 1, 0.5));
		
		var parent = new Sprite();
		var child = new Sprite();
		
		this.addChild(parent);
		parent.addChild(new Bitmap(bd1));
		parent.addChild(child);
		
		child.addChild(new Bitmap(bd2));
		parent.rotation = 10;
		parent.scaleX   = 1.2;
		child.scaleX    = 0.5;	
		
		trace("Before moving child");
		trace("\tParent data: (w, h, bounds)", parent.width, parent.height, parent.getBounds(null));
		trace("\tChild  data: (w, h, bounds)", child.width,  child.height,  child.getBounds(null) );
		child.x = parent.width - 100;
		child.y = parent.height - 100;
		trace("After moving child");
		trace("\tParent data: (w, h, bounds)", parent.width, parent.height, parent.getBounds(null));
		trace("\tChild  data: (w, h, bounds)", child.width,  child.height,  child.getBounds(null) );
	}
```

### CODE REVIEW

**Comment by mrcdk** [comment]
Also, fixed `scrollRect` position:

```haxe
child.scrollRect = new Rectangle(300, 300, 100, 100);
```

scrollRect

**Comment by mrcdk** [comment]
OK, I made the changes to the canvas render too:

After & Flash:
after image
Before:
before image
Notice that the red circle isn't rendered and the error

**Comment by mrcdk** [comment]
OK, I fixed the scrollRect hierarchy between parent and child displayObjects, it was broken before.

After & Flash:
after image

Before:
before image
notice that the green image isn't clipped

**Comment by Hasufel** [comment]
Great job Justo!

**Comment by mrcdk** [comment]
Right now the `scrollRect` won't rotate when using the openGL render. We are using `glScissor` to clip the objects when using a `scrollRect` and this function only clips on window coordinates.
This problem also happens on `legacy`.

Flash & next:
Flash and next

legacy:
legacy

Once this gets merged and I can continue to work on the shader+cacheAsBitmap branch, I think we can fix this problem.

**Pull request merged**
