### PR TITLE
DOM: Improve DOM text renderer.

### PR DESCRIPTION
**Pull request by rainyt**
1. Fix the problem that tap focus cannot be input.

2. When repairing the input, the default color is incorrect.

3. When clicking a text box other than text, the cursor positioning is wrong.

4. Support for password segment is added, but this requires a TTF, which I haven't handled yet.

5. Fix the problem of IME input.

6. Fix the problem that textfield did not get the text update in time.

### CODE REVIEW

**Comment by rainyt** [comment]
Password is not perfect, but others are good.

**Comment by rainyt** [comment]
For the rendering of password, I want to use the input tag. https://github.com/openfl/openfl/pull/2468

**Comment by ShaharMS** [comment]
Any reason why this isnt merged?

**Comment by rainyt** [comment]
Now it seems that it still has some defects, under certain circumstances. The input cursor sometimes returns to the first position.

**Comment by rainyt** [comment]
I can no longer guarantee that it will function properly

**Pull request closed without merging**
