### PR TITLE
Custom shaders

### PR DESCRIPTION
**Pull request by mrcdk**
This PR adds custom shader support for `DisplayObject.shader` and `Tilesheet.drawTiles()` on next.
It also adds support for `DisplayObject.cacheAsBitmap`

**Custom shaders aren't compatible with legacy, Flash or HTML5 canvas.**

I'll make a sample of how to use them later (I'm open to ideas :sweat_smile:)

### CODE REVIEW

**Comment by mrcdk** [comment]
More info:
* You can only edit fragment shaders.
* The shader will be applied to each child unless `cacheAsBitmap` is used. The same happens for `drawTiles()`
* Again, you can't use the same code for legacy, Flash or HTML5 canvas. You will need to guard it using conditional compilation.
* `cacheAsBitmap` is implemented caching the `DisplayObject` without any transformation applied and, then, applying them on the cached bitmap when rendering it.

**Comment by Hasufel** [comment]
+1 @mrcdk , great work! Looking forward to some samples - (some distortion or some effect on bunnymark using drawTiles would be cool)

**Comment by mrcdk** [comment]
Let's wait for the sample before merging this. I'm still tweaking it.

**Comment by larsiusprime** [comment]
Who's working on "the sample" ?

On Thu, Jun 4, 2015 at 2:36 PM, Justo Delgado <notifications@github.com>
wrote:

> Let's wait for the sample before merging this. I'm still tweaking it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfl/openfl/pull/697#issuecomment-109021996>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by Hasufel** [comment]
Justo is :)

**Comment by mrcdk** [comment]
Me, I'm editing bunnymark with some shaders but it's pretty ugly right now :sweat_smile: 

oh

**Comment by Hasufel** [comment]
uglytiful :+1:

**Comment by Beeblerox** [comment]
maybe it's stupid question, but is it possible to add custom shader support for graphics.drawTriangles()?

**Comment by james4k** [comment]
Please don't merge this until it can be reviewed with consideration for console support. Or, at least don't fall in love with the API.

**Comment by larsiusprime** [comment]
@RobDangerous just put the slides+text from his WWX talk:
http://tech.ktxsoftware.com/wwx-new-part-3-the-slides/

In case the details about Krafix in there reveal something that might be useful for us here.

**Comment by mrcdk** [comment]
Yay! macro time!
```haxe
class MyShader extends Shader {

	// Created by inigo quilez - iq/2015
	// License Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.
	// https://www.shadertoy.com/view/Ml2GWy
	@fragment var code = [
	'uniform float uZoom;',
	'uniform float uGlobalTime;',
	// only for testing :D
	'uniform vec4 uVec4;',
	'uniform mat4 uMat4;',
	'uniform bool uBool;',
	'uniform sampler2D uSampler2;',
	'void main() {',
	'    vec2 pos = 256.0*gl_FragCoord.xy/uZoom;',
	'    vec3 col = vec3(0.0);',
	'    for( int i=0; i<6; i++ ) ',
	'    {',
	'        vec2 a = floor(pos);',
	'        vec2 b = fract(pos);',
	'        vec4 w = fract((sin(a.x*7.0+31.0*a.y + 0.01*uGlobalTime)+vec4(0.035,0.01,0.0,0.7))*13.545317); // randoms',
	'        col += w.xyz *                                   // color',
	'               smoothstep(0.45,0.55,w.w) *               // intensity',
	'               sqrt( 16.0*b.x*b.y*(1.0-b.x)*(1.0-b.y) ); // pattern',
	'        pos /= 2.0; // lacunarity',
	'        col /= 2.0; // attenuate high frequencies',
	'    }',
	'    col = pow( 2.5*col, vec3(1.0,1.0,0.7) );    // contrast and color shape',
	'    gl_FragColor = colorTransform(vec4( col, 1.0 ), ${Shader.vColor}, ${Shader.uColorMultiplier}, ${Shader.uColorOffset});',
	'}',
	];
	
	public function new() {
		super();
	}
}
```
autocompletion

**Comment by TommyX12** [comment]
Hey, this looks fantastic! Just one question, is it possible to implement multi-pass sharers? Does it use FBOs?

**Comment by mrcdk** [comment]
Yes, multi-pass will be possible using filters, I'm working on this right now but I'm pretty busy with other stuff.
It uses FBOs when `cacheAsBitmap` is true. Filters force it to be true.
Right now, if you play with `cacheAsBitmap` and sprites you can have it, kind of. (There are a few things that I have to fix before though :sweat_smile:)
example
A Sprite with two children with a rgb shift shader and `cacheAsBitmap = true`, the right child have a dot shader.

**Comment by TommyX12** [comment]
Nice job man, also by multipass I mean having multiple textures where you can set render target to, then manipulate etc. Any ways we can replicate that using the filter system?

**Comment by TheSHEEEP** [comment]
Great to see that someone is working on this! 
*keeping an eye on this*

**Comment by mrcdk** [comment]
I've opened a PR with a few examples here https://github.com/openfl/openfl-samples/issues/28

**Comment by mrcdk** [comment]
I would say this is pretty much done, apart from adding more filters and finding possible bugs or incoherences with Flash (even though Flash doesn't support much of what this PR have :sweat_smile:) Still, I would appreciate some more testing before merging it.

**Comment by jgranick** [comment]
Any way to fix the unit test? Like an #if neko in the test if the closure error is not an issue?

**Comment by mrcdk** [comment]
AFAIK it's a neko limitation and I'm not sure how to fix it. It's not a real issue, I've been testing the changes with neko and windows builds

**Comment by jgranick** [comment]
If it is something like this:

```haxe
var drawTiles = sprite.graphics.drawTiles;
Assert.isNotNull (drawTiles);
```

Then it could just be changed to something like this for now:

```haxe
#if !neko
var drawTiles = sprite.graphics.drawTiles;
Assert.isNotNull (drawTiles);
#end
```

I want to make sure there are no other problems obscured behind a failing unit test due to Neko's max closure length :wink:

**Comment by mrcdk** [comment]
On yeah, I guess that would work, I'll do it tomorrow

**Comment by mrcdk** [comment]
I've updated the samples with a Tilesheet example https://github.com/openfl/openfl-samples/pull/28

**Comment by mrcdk** [comment]
Ok, so far the following filters are *"done"*:
- `ShaderFilter`: There is no much to say about this one, it just accepts a `Shader` and applies it to the cached bitmap.
- `ColorMatrixFilter`: Same output as Flash (as far as I know :sweat_smile:)
- `BlurFilter`: It doesn't give the same output as Flash with the same settings, but tweaking a bit the `blurX`, `blurY` and `quality` it can come close to it.
- `GlowFilter`: It has the same *problem* as `BlurFilter` with the blur settings. I don't really know what `strength` does,  `inner` isn't implemented and `knockout` just hides the original bitmap.
- `DropShadowFilter`: It has the same *problems* as `GlowFilter`.

**Comment by jcward** [comment]
Wow, great work, I can't wait to play with this! The ability to apply bits of shader magic in the context of a nice framework like OpenFL will be sweet!

**Comment by mrcdk** [comment]
Don't merge this yet, `scrollRect`s are broken, they mess with everything. We need to have them working before trying to merge this.

**Comment by aW4KeNiNG** [comment]
Great work! I can't wait to play with it!

**Comment by mtari** [comment]
I can't wait to try this feature.

**Comment by mumeka** [comment]
Keep up the good work!

**Comment by TheSHEEEP** [comment]
I am assuming that https://github.com/openfl/openfl/pull/828 will help with this?
Great that you are still workingon this :)

**Comment by mrcdk** [comment]
This needs a lot of work to bring back, I'm closing it and will open a new PR soon.

**Comment by larsiusprime** [comment]
you can do it! We believe in you!

**Comment by Hasufel** [comment]
Go Justo!

**Comment by TheSHEEEP** [comment]
Sweeeet!

**Comment by er453r** [comment]
This broke with newer lime https://github.com/openfl/openfl/issues/960

Any ideas how to fix this? I'm using shaders a lot....

**Pull request closed without merging**
