### PR TITLE
Fixes ColorMatrixFilter

### LINKED ISSUE #1049: Re-enable ColorMatrixFilter after a bad commit
This commit broke ColorMatrixFilter, just uncommenting these 2 lines fixes it -> https://github.com/openfl/openfl/commit/4973db4094e50552ff12c6e6928141bd2f346249#diff-d7890a18e2f5fea2df16f6edeb7e830eR101

### PR DESCRIPTION
**Pull request by er453r**
Fixes https://github.com/openfl/openfl/issues/1049

### CODE REVIEW

**Comment by loudoweb** [comment]
thanks ! It works.

**Comment by ibilon** [comment]
@er453r @loudoweb got a code sample I could test this with?

**Comment by loudoweb** [comment]
//add a bitmap into a sprite (or draw into it) and then...
//sepia
var matrix = Array<Float> = [	
	0.393, 0.7689999, 0.18899999, 0, 0,
	0.349, 0.6859999, 0.16799999, 0, 0,
	0.272, 0.5339999, 0.13099999, 0, 0,
	0, 0, 0, 1, 0
];
sprite.filters = [new ColorMatrixFilter(matrix)];

**Comment by ibilon** [comment]
That does indeed fix it,
thanks for the contribution!

**Pull request merged**
