### PR TITLE
Don't crash when weird text layout bugs arise

### PR DESCRIPTION
**Pull request by MSGhero**
Feel free to suggest a better warning message.

### CODE REVIEW

**Comment by Gama11** [comment]
How about:

>You found a bug in OpenFL's text code! Your project has automatically been zipped and sent to Joshua Granick (@singmajesty) so we can fix this.

**Comment by MSGhero** [comment]
I don't think people in copyright-land would appreciate sending their project off without permission.

**Comment by Gama11** [comment]
I guess I forgot the sarcasm tag. x)

**Comment by jgranick** [comment]
It's like winning the lottery!

**Pull request merged**
